citadel_version: 4

metadata:
  name: Blind Oracle
  version: 0.0.1
  category: bitcoin
  tagline: Encrypt your wallet on Blockstream Jade
  description: |
    Run a personal blind oracle to encrypt the wallet material on your 
    Blockstream Jade.

    Your blind oracle holds the decryption key to your Jade that is needed 
    to unlock your device. This allows your Jade to remain protected from 
    physical key extraction while also enforcing a maximum of 3 PIN attempts. 
    Your blind oracle does not learn any sensitive information and does not 
    know anything about the wallet on Jade.
  developers: 
    Blockstream: https://blockstream.com
  permissions: []
  repo:
    blind_pin_server: https://github.com/Blockstream/blind_pin_server
  support: https://t.me/blockstream_jade
  gallery:
    - https://i.imgur.com/u5H5E1w.jpeg
  submitter: Valerio Vaccaro

services:
  node:
    image: tulipan81/blind_pin_server:v0.0.2@sha256:c3d32ac20594af9303de1971d014f39929a76efd4aa9717bedb77814117e1f98
    depends_on:
      - web
    restart: on-failure
    stop_grace_period: 1m
    required_ports:
      tcp:
        8096: 8096
    hidden_services:
      8096: 8096
    mounts:
      data:
        data/server_public_key.pub: /app/server_public_key.pub
        data/server_private_key.key: /app/server_private_key.key
        data/pins: /app/pins
  web:
    image: tulipan81/pinserver_web:v0.0.15@sha256:4cba37193f918e8fc91a124a222e05ca35630a31094ded18139d4bab128275b8
    restart: on-failure
    port: 8081
    mounts:
      data:
        data/server_public_key.pub: /app/server_public_key.pub
        data/server_private_key.key: /app/server_private_key.key
        data/pins: /app/pins
    environment:
      PINSERVER_URL: ${APP_HIDDEN_SERVICE}
      PINSERVER_PORT: "8096"